# Generated by Django 5.0.4 on 2024-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('1', 'Аттестат об основном общем образовании'), ('2', 'Аттестат о среднем общем образовании'), ('3', 'Диплом СПО')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('РФ', 'Паспорт гражданина РФ'), ('ИНО', 'Паспорт иностранного гражданина')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduDoc', models.ManyToManyField(to='main.edumodel')),
                ('identityDoc', models.ManyToManyField(to='main.identitymodel')),
            ],
        ),
    ]
